### ISSUE TITLE
'locale.Error: unsupported locale setting' while installing accelerometer

### ISSUE THREAD

**Issue by ghost** [qwazwsx/Advanced-SonicPad#1]
Hello,

Im not getting the Accelerometer tester installed for some reason, can you maybe help? 

```
sonic@SonicPad:~$ cd ~/klipper
make clean
make menuconfig # select "linux process"
make flash
  Creating symbolic link out/board
Loaded configuration '/home/sonic/klipper/.config'
Traceback (most recent call last):
  File "/home/sonic/klipper/lib/kconfiglib/menuconfig.py", line 3281, in <module>
    _main()
  File "/home/sonic/klipper/lib/kconfiglib/menuconfig.py", line 661, in _main
    menuconfig(standard_kconfig(__doc__))
  File "/home/sonic/klipper/lib/kconfiglib/menuconfig.py", line 705, in menuconfig
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
make: *** [Makefile:116: menuconfig] Error 1
  Building out/autoconf.h
  Compiling out/src/sched.o
  Compiling out/src/command.o
  Compiling out/src/basecmd.o
  Compiling out/src/debugcmds.o
  Compiling out/src/initial_pins.o
  Compiling out/src/gpiocmds.o
  Compiling out/src/stepper.o
  Compiling out/src/endstop.o
  Compiling out/src/trsync.o
  Compiling out/src/adccmds.o
  Compiling out/src/spicmds.o
  Compiling out/src/i2ccmds.o
  Compiling out/src/pwmcmds.o
  Compiling out/src/buttons.o
  Compiling out/src/tmcuart.o
  Compiling out/src/neopixel.o
  Compiling out/src/pulse_counter.o
  Compiling out/src/lcd_st7920.o
  Compiling out/src/lcd_hd44780.o
  Compiling out/src/spi_software.o
  Compiling out/src/i2c_software.o
  Compiling out/src/thermocouple.o
  Compiling out/src/sensor_adxl345.o
  Compiling out/src/sensor_angle.o
  Compiling out/src/sensor_mpu9250.o
  Compiling out/src/sensor_lis2dw.o
  Compiling out/src/sensor_bulk.o
  Compiling out/src/avr/main.o
  Compiling out/src/avr/timer.o
  Compiling out/src/avr/gpio.o
  Compiling out/src/avr/adc.o
  Compiling out/src/avr/spi.o
  Compiling out/src/avr/i2c.o
  Compiling out/src/avr/hard_pwm.o
  Compiling out/src/avr/watchdog.o
  Compiling out/src/avr/serial.o
  Compiling out/src/generic/serial_irq.o
  Building out/compile_time_request.o
Version: v0.12.0-114-ga77d0790
  Linking out/klipper.elf
  Creating hex file out/klipper.elf.hex
  Flashing out/klipper.elf.hex to  via avrdude
Please specify FLASH_DEVICE
make: *** [src/avr/Makefile:33: flash] Error 1
sonic@SonicPad:~/klipper$ make clean
sonic@SonicPad:~/klipper$ make configmenu
  Creating symbolic link out/board
make: *** No rule to make target 'configmenu'.  Stop.
sonic@SonicPad:~/klipper$ make menuconfig #
Loaded configuration '/home/sonic/klipper/.config'
Traceback (most recent call last):
  File "/home/sonic/klipper/lib/kconfiglib/menuconfig.py", line 3281, in <module>
    _main()
  File "/home/sonic/klipper/lib/kconfiglib/menuconfig.py", line 661, in _main
    menuconfig(standard_kconfig(__doc__))
  File "/home/sonic/klipper/lib/kconfiglib/menuconfig.py", line 705, in menuconfig
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
make: *** [Makefile:116: menuconfig] Error 1
sonic@SonicPad:~/klipper$ sudo cp ~klipper/scripts/klipper-mcu.service /etc/systemd/system/
cp: cannot stat '~klipper/scripts/klipper-mcu.service': No such file or directory
sonic@SonicPad:~/klipper$ cd
sonic@SonicPad:~$ sudo cp ~klipper/scripts/klipper-mcu.service /etc/systemd/system/
cp: cannot stat '~klipper/scripts/klipper-mcu.service': No such file or directory
sonic@SonicPad:~$ cd klipper
sonic@SonicPad:~/klipper$ sudo cp ~klipper/scripts/klipper-mcu.service /etc/systemd/system/
cp: cannot stat '~klipper/scripts/klipper-mcu.service': No such file or directory
sonic@SonicPad:~/klipper$ 
```

**Comment by officiallyemma** [comment]
I'd like to clarify that I did not create the SonicPad-Debian project, I'm just the one who made this tutorial. 


Crux of the issue seems to be with python localization in the `$ make menuconfig` command.

Try to update and upgrade all packages, then restart and retry.
`sudo apt-get update && sudo apt-get upgrade`

What is the output of
```
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
```
(as per https://stackoverflow.com/a/36257050)

Does it work after running the above command?

**Comment by ghost** [comment]
Thanks Tony! Let me check that!

**Comment by DDen87** [comment]
@qwazwsx unfortunately it seems that the language is not set? I don't know how to set it up in the screen it shows:
`~$ export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory

Package configuration

 ┌──────────────────────────┤ Configuring locales ├──────────────────────────┐
 │ Locales are a framework to switch between multiple languages and allow    │ 
 │ users to use their language, country, characters, collation order, etc.   │ 
 │                                                                           │ 
 │ Please choose which locales to generate. UTF-8 locales should be chosen   │ 
 │ by default, particularly for new installations. Other character sets may  │ 
 │ be useful for backwards compatibility with older systems and software.    │ 
 │                                                                           │ 
 │ Locales to be generated:                                                  │ 
 │                                                                           │ 
 │    [ ] All locales                                                        │ 
 │    [ ] aa_DJ ISO-8859-1                                                   │ 
 │    [ ] aa_DJ.UTF-8 UTF-8                                              ▒   │ 
 │    [ ] aa_ER UTF-8                                                    ▒   │ 
 │    [ ] aa_ER@saaho UTF-8                                                  │ 
 │                                                                           │ 
 │                                                                           │ 
 │                    <Ok>                        <Cancel>                   │ 
 │                                                                           │ 
 └───────────────────────────────────────────────────────────────────────────┘ 
                                                                               

`

**Comment by ghost** [comment]
Thanks @qwazwsx !
I got figured out that the Language en_US..UTF-8 was not selected/configured. Did that and got everything installed! Thanks again!

**Comment by officiallyemma** [comment]
Glad I could point you in the right direction troubleshooting. Happy printing!
